### ISSUE TITLE
我是那个一键脚本的萌新作者（╯－_－）╯╧╧

### ISSUE THREAD

**Issue by godzlalala** [maysrp/yunBT#2]
首先再次感谢大佬开源，我只是把安装步骤整合起来了而已，由于对NGINX PHP的配置不太熟，可能显得比较傻，大佬们可以根据自己的需要优（改）化（对），也希望大佬能够继续更新完善。小弟也可以多学（抄）习（袭）一点知识。。。再次感谢大佬开源QAQ

**Comment by maysrp** [comment]
已经添加一件安装刀readme
不 ~我只是渣渣而已
