### ISSUE TITLE
如何修改下载位置和Aria2配置？

### ISSUE THREAD

**Issue by 66q** [maysrp/yunBT#6]
可以手动指定下载目录和Aria2端口吗？

**Comment by maysrp** [comment]
修改aria2.conf的配置。文件在/root/.aria2/aria2.conf 
里面是GBK编码的有中文注释可以修改默认下载目录（yunbt在下载是是自动下载到你的public下的目录，无须设置默认）和端口然后重启aria2即可。

**Comment by 66q** [comment]
不可以修改yunbt的下载位置/手动指定Aria2端口吗？

**Comment by maysrp** [comment]
Aria2 的下载端口可以手动修改 ，修改了需要将yunbt 中simplewind/cmf/common.php 中有关aria2的连接修改，还要修改python/cron_download.py的aria2连接端口。
下载位置yunbt是指定到 public/file/download/文件夹的。
要该的话可能要修改许多代码:
 app/user/controller/MagnetController.php
